2024-02-18 20:09:18,536 INFO    MainThread:3658137 [wandb_setup.py:_flush():69] setting env: {}
2024-02-18 20:09:18,537 INFO    MainThread:3658137 [wandb_setup.py:_flush():69] setting login settings: {}
2024-02-18 20:09:18,537 INFO    MainThread:3658137 [wandb_init.py:_log_setup():337] Logging user logs to /trinity/home/a.kolesov/NOTBarycenters/stylegan2/notebooks/wandb/run-20240218_200918-3rzkma53/logs/debug.log
2024-02-18 20:09:18,537 INFO    MainThread:3658137 [wandb_init.py:_log_setup():338] Logging internal logs to /trinity/home/a.kolesov/NOTBarycenters/stylegan2/notebooks/wandb/run-20240218_200918-3rzkma53/logs/debug-internal.log
2024-02-18 20:09:18,538 INFO    MainThread:3658137 [wandb_init.py:_jupyter_setup():288] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x15546035aa60>
2024-02-18 20:09:18,538 INFO    MainThread:3658137 [wandb_init.py:init():370] calling init triggers
2024-02-18 20:09:18,538 INFO    MainThread:3658137 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {'K': 3, 'LAMBDAS': [0.25, 0.5, 0.25], 'DATASET_PATH': '../../../data/ave_celeba_green_v2/', 'DATASET': 'ave_celeba', 'BATCH_SIZE': 32, 'IMG_SIZE': 64, 'NC': 3, 'LR_POTENTIAL': 0.0002, 'LR_ENCODER': 0.0002, 'BETAS': (0.2, 0.99), 'FLAG_LATENT': True, 'ZC': 1, 'LATENT_SIZE': 512, 'GENERATOR_PATH': '../../../stylegan2_ada_pytorch_before/training-runs/00011-aligned_celeba-stylegan2/network-snapshot-008800.pkl', 'NUM_EPOCHS': 1, 'INNER_ITERATIONS': 10, 'GAMMA': 0.1, 'WEIGHT_NORM': 0.1, 'Z_STD': 0.1, 'RESNET_ENCODER_LATENT': 2, 'GPU_DEVICE': 0, 'DEVICE': 'cuda:0', 'NAME_EXP': 'Dist_GAMMA_0.1_Z_STD_0.1_BS_32_NZ_2'}
2024-02-18 20:09:18,538 INFO    MainThread:3658137 [wandb_init.py:init():419] starting backend
2024-02-18 20:09:18,538 INFO    MainThread:3658137 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-18 20:09:18,553 INFO    MainThread:3658137 [backend.py:ensure_launched():135] starting backend process...
2024-02-18 20:09:18,565 INFO    MainThread:3658137 [backend.py:ensure_launched():139] started backend process with pid: 3666265
2024-02-18 20:09:18,567 INFO    MainThread:3658137 [wandb_init.py:init():424] backend started and connected
2024-02-18 20:09:18,613 INFO    MainThread:3658137 [wandb_run.py:_label_probe_notebook():844] probe notebook
2024-02-18 20:09:18,614 INFO    MainThread:3658137 [wandb_run.py:_label_probe_notebook():851] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-18 20:09:18,614 INFO    MainThread:3658137 [wandb_init.py:init():472] updated telemetry
2024-02-18 20:09:18,618 INFO    MainThread:3658137 [wandb_init.py:init():491] communicating current version
2024-02-18 20:09:19,295 INFO    MainThread:3658137 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.16.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-02-18 20:09:19,296 INFO    MainThread:3658137 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2024-02-18 20:09:19,589 INFO    MainThread:3658137 [wandb_init.py:init():529] starting run threads in backend
2024-02-18 20:09:20,324 INFO    MainThread:3658137 [wandb_run.py:_console_start():1623] atexit reg
2024-02-18 20:09:20,325 INFO    MainThread:3658137 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.WRAP
2024-02-18 20:09:20,325 INFO    MainThread:3658137 [wandb_run.py:_redirect():1534] Wrapping output streams.
2024-02-18 20:09:20,326 INFO    MainThread:3658137 [wandb_run.py:_redirect():1558] Redirects installed.
2024-02-18 20:09:20,326 INFO    MainThread:3658137 [wandb_init.py:init():554] run started, returning control to user process
2024-02-18 20:09:20,329 INFO    MainThread:3658137 [wandb_init.py:_pause_backend():250] pausing backend
2024-02-18 20:09:20,330 INFO    MainThread:3658137 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2024-02-18 20:09:20,333 INFO    MainThread:3658137 [wandb_init.py:_resume_backend():259] resuming backend
2024-02-18 20:09:43,929 INFO    MainThread:3658137 [wandb_init.py:_pause_backend():250] pausing backend
2024-02-18 20:09:43,930 INFO    MainThread:3658137 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2024-02-18 20:10:33,725 INFO    MainThread:3658137 [wandb_run.py:_atexit_cleanup():1593] got exitcode: 0
2024-02-18 20:10:37,825 INFO    MainThread:3658137 [wandb_run.py:_restore():1565] restore
2024-02-18 20:10:38,427 INFO    MainThread:3658137 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3414703
  total_bytes: 3414703
}

